int _putchar(char);
void reset_to_98(int *);
void swap_int(int *, int *);
int _strlen(char *);
void _puts(char *str);
void print_rev(char *s);
void rev_string(char *s);
void puts2(char *);
void puts_half(char *);
void print_array(int *, int);
char *_strcpy(char *dest, char *src);
